// src/components/AppFooter.tsx
import Link from 'next/link'

const productLinks = [{ name: 'All Products', path: '/products' }]

const companyLinks = [
  { name: 'About', path: '/about' },
  { name: 'Technologies', path: '/technologies' },
  { name: 'Careers', path: '/careers' },
  { name: 'Contact', path: '/contact' },
]

const legalLinks = [
  { name: 'Privacy Policy', path: '/privacy' },
  { name: 'Terms of Service', path: '/terms' },
  { name: 'Cookie Policy', path: '/cookies' },
]

export function AppFooter() {
  const currentYear = new Date().getFullYear()

  return (
    <footer className="border-t border-gray-200 bg-white dark:border-gray-700 dark:bg-gray-800">
      <div className="container mx-auto px-4 py-12 sm:px-6 lg:px-8">
        <div className="grid grid-cols-1 gap-8 md:grid-cols-4">
          {/* Logo and about section */}
          <div className="col-span-1">
            <div className="mb-4 flex items-center space-x-2">
              <div className="flex h-9 w-9 items-center justify-center overflow-hidden rounded bg-gradient-to-br from-indigo-600 to-purple-600">
                <span className="text-2xl">🦋</span>
              </div>
              <span className="text-xl font-bold text-gray-900 dark:text-white">Sylphx</span>
            </div>
            <p className="mb-4 text-sm text-gray-600 dark:text-gray-400">
              Simple, elegant & usable software. Creating digital products that empower without
              overwhelming.
            </p>
            <div className="flex space-x-4">
              <a
                href="https://twitter.com/sylphxlab"
                target="_blank"
                rel="noopener noreferrer"
                className="text-gray-500 transition-colors hover:text-indigo-600 dark:text-gray-400 dark:hover:text-indigo-400"
                aria-label="Twitter"
              >
                <svg className="h-5 w-5" fill="currentColor" viewBox="0 0 24 24">
                  <path d="M8.29 20.251c7.547 0 11.675-6.253 11.675-11.675 0-.178 0-.355-.012-.53A8.348 8.348 0 0022 5.92a8.19 8.19 0 01-2.357.646 4.118 4.118 0 001.804-2.27 8.224 8.224 0 01-2.605.996 4.107 4.107 0 00-6.993 3.743 11.65 11.65 0 01-8.457-4.287 4.106 4.106 0 001.27 5.477A4.072 4.072 0 012.8 9.713v.052a4.105 4.105 0 003.292 4.022 4.095 4.095 0 01-1.853.07 4.108 4.108 0 003.834 2.85A8.233 8.233 0 012 18.407a11.616 11.616 0 006.29 1.84" />
                </svg>
              </a>
              <a
                href="https://github.com/sylphxltd"
                target="_blank"
                rel="noopener noreferrer"
                className="text-gray-500 transition-colors hover:text-indigo-600 dark:text-gray-400 dark:hover:text-indigo-400"
                aria-label="GitHub"
              >
                <svg className="h-5 w-5" fill="currentColor" viewBox="0 0 24 24">
                  <path
                    fillRule="evenodd"
                    d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z"
                    clipRule="evenodd"
                  />
                </svg>
              </a>
            </div>
          </div>

          {/* Products section */}
          <div className="col-span-1">
            <h3 className="mb-4 text-sm font-semibold uppercase tracking-wider text-gray-900 dark:text-white">
              Products
            </h3>
            <ul className="space-y-3">
              {productLinks.map((link) => (
                <li key={link.path}>
                  <Link
                    href={link.path}
                    className="text-gray-600 transition-colors hover:text-indigo-600 dark:text-gray-400 dark:hover:text-indigo-400"
                  >
                    {link.name}
                  </Link>
                </li>
              ))}
            </ul>
          </div>

          {/* Company section */}
          <div className="col-span-1">
            <h3 className="mb-4 text-sm font-semibold uppercase tracking-wider text-gray-900 dark:text-white">
              Company
            </h3>
            <ul className="space-y-3">
              {companyLinks.map((link) => (
                <li key={link.path}>
                  <Link
                    href={link.path}
                    className="text-gray-600 transition-colors hover:text-indigo-600 dark:text-gray-400 dark:hover:text-indigo-400"
                  >
                    {link.name}
                  </Link>
                </li>
              ))}
            </ul>
          </div>

          {/* Legal section */}
          <div className="col-span-1">
            <h3 className="mb-4 text-sm font-semibold uppercase tracking-wider text-gray-900 dark:text-white">
              Legal
            </h3>
            <ul className="space-y-3">
              {legalLinks.map((link) => (
                <li key={link.path}>
                  <Link
                    href={link.path}
                    className="text-gray-600 transition-colors hover:text-indigo-600 dark:text-gray-400 dark:hover:text-indigo-400"
                  >
                    {link.name}
                  </Link>
                </li>
              ))}
            </ul>
          </div>
        </div>

        {/* Copyright */}
        <div className="mt-8 border-t border-gray-200 pt-8 dark:border-gray-700">
          <p className="text-center text-sm text-gray-500 dark:text-gray-400">
            © {currentYear} Sylphx. All rights reserved.
          </p>
        </div>
      </div>
    </footer>
  )
}

// components/AppFooter.vue
<template>
  <footer class="bg-white dark:bg-gray-800 border-t border-gray-200 dark:border-gray-700">
    <div class="container mx-auto px-4 sm:px-6 lg:px-8 py-12">
      <div class="grid grid-cols-1 md:grid-cols-4 gap-8">
        <!-- Logo and about section -->
        <div class="col-span-1 md:col-span-1">
          <div class="flex items-center space-x-2 mb-4">
            <div class="h-9 w-9 flex items-center justify-center rounded overflow-hidden bg-gradient-to-br from-indigo-600 to-purple-600">
              <img src="/images/logo.png" alt="SylphX Logo" class="h-6 w-6">
            </div>
            <span class="text-xl font-bold text-gray-900 dark:text-white">SylphX</span>
          </div>
          <p class="text-gray-600 dark:text-gray-400 text-sm mb-4">
            Innovative cross-platform applications and immersive experiences powered by cutting-edge technologies.
          </p>
          <div class="flex space-x-4">
            <a href="#" class="text-gray-500 hover:text-indigo-600 dark:text-gray-400 dark:hover:text-indigo-400 transition-colors">
              <span class="i-carbon-logo-twitter text-xl"></span>
              <span class="sr-only">Twitter</span>
            </a>
            <a href="#" class="text-gray-500 hover:text-indigo-600 dark:text-gray-400 dark:hover:text-indigo-400 transition-colors">
              <span class="i-carbon-logo-facebook text-xl"></span>
              <span class="sr-only">Facebook</span>
            </a>
            <a href="#" class="text-gray-500 hover:text-indigo-600 dark:text-gray-400 dark:hover:text-indigo-400 transition-colors">
              <span class="i-carbon-logo-instagram text-xl"></span>
              <span class="sr-only">Instagram</span>
            </a>
            <a href="#" class="text-gray-500 hover:text-indigo-600 dark:text-gray-400 dark:hover:text-indigo-400 transition-colors">
              <span class="i-carbon-logo-github text-xl"></span>
              <span class="sr-only">GitHub</span>
            </a>
          </div>
        </div>
        
        <!-- Products section -->
        <div class="col-span-1">
          <h3 class="text-sm font-semibold text-gray-900 dark:text-white uppercase tracking-wider mb-4">
            Products
          </h3>
          <ul class="space-y-3">
            <li>
              <NuxtLink to="/apps" class="text-gray-600 dark:text-gray-400 hover:text-indigo-600 dark:hover:text-indigo-400 transition-colors">
                All Products
              </NuxtLink>
            </li>
            <li>
              <NuxtLink to="/apps/sylph-note" class="text-gray-600 dark:text-gray-400 hover:text-indigo-600 dark:hover:text-indigo-400 transition-colors">
                SylphNote
              </NuxtLink>
            </li>
            <li>
              <NuxtLink to="/apps/vortex-vr" class="text-gray-600 dark:text-gray-400 hover:text-indigo-600 dark:hover:text-indigo-400 transition-colors">
                VortexVR
              </NuxtLink>
            </li>
            <li>
              <NuxtLink to="/apps/sylph-chat" class="text-gray-600 dark:text-gray-400 hover:text-indigo-600 dark:hover:text-indigo-400 transition-colors">
                SylphChat
              </NuxtLink>
            </li>
          </ul>
        </div>
        
        <!-- Company section -->
        <div class="col-span-1">
          <h3 class="text-sm font-semibold text-gray-900 dark:text-white uppercase tracking-wider mb-4">
            Company
          </h3>
          <ul class="space-y-3">
            <li>
              <NuxtLink to="/about" class="text-gray-600 dark:text-gray-400 hover:text-indigo-600 dark:hover:text-indigo-400 transition-colors">
                About Us
              </NuxtLink>
            </li>
            <li>
              <NuxtLink to="/technologies" class="text-gray-600 dark:text-gray-400 hover:text-indigo-600 dark:hover:text-indigo-400 transition-colors">
                Technologies
              </NuxtLink>
            </li>
            <li>
              <NuxtLink to="/contact" class="text-gray-600 dark:text-gray-400 hover:text-indigo-600 dark:hover:text-indigo-400 transition-colors">
                Contact
              </NuxtLink>
            </li>
            <li>
              <NuxtLink to="/careers" class="text-gray-600 dark:text-gray-400 hover:text-indigo-600 dark:hover:text-indigo-400 transition-colors">
                Careers
              </NuxtLink>
            </li>
          </ul>
        </div>
        
        <!-- Legal section -->
        <div class="col-span-1">
          <h3 class="text-sm font-semibold text-gray-900 dark:text-white uppercase tracking-wider mb-4">
            Legal
          </h3>
          <ul class="space-y-3">
            <li>
              <NuxtLink to="/privacy" class="text-gray-600 dark:text-gray-400 hover:text-indigo-600 dark:hover:text-indigo-400 transition-colors">
                Privacy Policy
              </NuxtLink>
            </li>
            <li>
              <NuxtLink to="/terms" class="text-gray-600 dark:text-gray-400 hover:text-indigo-600 dark:hover:text-indigo-400 transition-colors">
                Terms of Service
              </NuxtLink>
            </li>
            <li>
              <NuxtLink to="/cookies" class="text-gray-600 dark:text-gray-400 hover:text-indigo-600 dark:hover:text-indigo-400 transition-colors">
                Cookie Policy
              </NuxtLink>
            </li>
          </ul>
        </div>
      </div>
      
      <!-- Bottom section with copyright -->
      <div class="mt-12 pt-8 border-t border-gray-200 dark:border-gray-700">
        <div class="flex flex-col md:flex-row justify-between items-center">
          <p class="text-sm text-gray-600 dark:text-gray-400">
            © {{ new Date().getFullYear() }} SylphX. All rights reserved.
          </p>
          <div class="mt-4 md:mt-0">
            <button @click="toggleTheme" class="text-sm text-gray-600 dark:text-gray-400 hover:text-indigo-600 dark:hover:text-indigo-400 transition-colors">
              <span v-if="isDark">
                <span class="i-carbon-sun inline-block align-text-bottom mr-1"></span>
                Switch to Light Mode
              </span>
              <span v-else>
                <span class="i-carbon-moon inline-block align-text-bottom mr-1"></span>
                Switch to Dark Mode
              </span>
            </button>
          </div>
        </div>
      </div>
    </div>
  </footer>
</template>

<script setup>
import { ref, onMounted } from 'vue';

// Check dark mode preference
const isDark = ref(false);

// Toggle theme
const toggleTheme = () => {
  isDark.value = !isDark.value;
  
  // Update class on document element
  if (isDark.value) {
    document.documentElement.classList.add('dark');
    localStorage.setItem('color-theme', 'dark');
  } else {
    document.documentElement.classList.remove('dark');
    localStorage.setItem('color-theme', 'light');
  }
};

// Initialize theme on mount
onMounted(() => {
  // Check local storage theme preference
  isDark.value = localStorage.getItem('color-theme') === 'dark' || 
    (!localStorage.getItem('color-theme') && window.matchMedia('(prefers-color-scheme: dark)').matches);
  
  // Apply theme
  if (isDark.value) {
    document.documentElement.classList.add('dark');
  } else {
    document.documentElement.classList.remove('dark');
  }
});
</script>
