// src/components/Toast.tsx
'use client'

import { useDeepMap } from '@/hooks/useZen'
import { getTimeLeftPercentage, removeToast, type ToastType, toastStore } from '@/stores/toast'

const toastStyles: Record<ToastType, { bg: string; border: string; icon: string }> = {
  success: {
    bg: 'bg-green-50 dark:bg-green-900/20',
    border: 'border-green-500',
    icon: '✓',
  },
  error: {
    bg: 'bg-red-50 dark:bg-red-900/20',
    border: 'border-red-500',
    icon: '✕',
  },
  warning: {
    bg: 'bg-yellow-50 dark:bg-yellow-900/20',
    border: 'border-yellow-500',
    icon: '⚠',
  },
  info: {
    bg: 'bg-blue-50 dark:bg-blue-900/20',
    border: 'border-blue-500',
    icon: 'ℹ',
  },
}

export function ToastContainer() {
  const state = useDeepMap(toastStore)

  if (state.toasts.length === 0) return null

  return (
    <div className="pointer-events-none fixed inset-0 z-50 flex flex-col items-end justify-end gap-2 p-4 sm:p-6">
      {state.toasts.map((toast) => {
        const style = toastStyles[toast.type]
        const percentage = getTimeLeftPercentage(toast)

        return (
          <div
            key={toast.id}
            className={`pointer-events-auto relative overflow-hidden rounded-lg border-l-4 ${style.border} ${style.bg} shadow-lg transition-all duration-300`}
          >
            <div className="flex items-start gap-3 p-4">
              <span className="text-xl">{style.icon}</span>
              <p className="flex-1 text-sm font-medium text-gray-900 dark:text-gray-100">
                {toast.message}
              </p>
              <button
                type="button"
                onClick={() => removeToast(toast.id)}
                className="text-gray-400 transition-colors hover:text-gray-600 dark:hover:text-gray-200"
                aria-label="Close"
              >
                ✕
              </button>
            </div>
            {toast.timeout > 0 && (
              <div className="h-1 bg-gray-200 dark:bg-gray-700">
                <div
                  className={`h-full ${style.border.replace('border', 'bg')} transition-all duration-100`}
                  style={{ width: `${percentage}%` }}
                />
              </div>
            )}
          </div>
        )
      })}
    </div>
  )
}

// components/Toast.vue
<template>
  <Teleport to="body">
    <TransitionGroup
      tag="div"
      name="toast"
      class="fixed z-50 top-4 right-4 flex flex-col gap-3 max-w-sm"
    >
      <div 
        v-for="toast in toastStore.toasts" 
        :key="toast.id"
        :class="[
          'px-4 py-3 rounded-lg shadow-lg backdrop-blur-sm animate-fadeIn', 
          toast.type === 'success' ? 'bg-green-500/90 text-white' : 
          toast.type === 'error' ? 'bg-red-500/90 text-white' : 
          toast.type === 'warning' ? 'bg-yellow-500/90 text-white' : 
          'bg-blue-500/90 text-white'
        ]"
      >
        <div class="flex items-start">
          <div class="flex-shrink-0 mr-2">
            <div v-if="toast.type === 'success'" class="i-carbon-checkmark-outline text-xl"></div>
            <div v-else-if="toast.type === 'error'" class="i-carbon-warning text-xl"></div>
            <div v-else-if="toast.type === 'warning'" class="i-carbon-warning-alt text-xl"></div>
            <div v-else class="i-carbon-information text-xl"></div>
          </div>
          <div class="flex-1 pr-6">
            <p class="font-medium">{{ toast.message }}</p>
          </div>
          <button 
            @click="toastStore.remove(toast.id)"
            class="flex-shrink-0 -mt-1 -mr-1 ml-auto text-white/80 hover:text-white"
          >
            <div class="i-carbon-close text-lg"></div>
          </button>
        </div>
        <!-- Progress bar -->
        <div 
          v-if="toast.timeout > 0" 
          class="h-1 bg-white/30 mt-2 rounded-full overflow-hidden"
        >
          <div 
            class="h-full bg-white/70 rounded-full" 
            :style="{ width: `${toastStore.getTimeLeftPercentage(toast)}%` }"
          ></div>
        </div>
      </div>
    </TransitionGroup>
  </Teleport>
</template>

<script setup lang="ts">
import { onMounted } from 'vue';
import { useToastStore } from '~/stores/toast';

export type ToastType = 'info' | 'success' | 'error' | 'warning';

const toastStore = useToastStore();

// Mount the Toast component globally when app starts
onMounted(() => {
  // Not needed - the state is managed directly in the Pinia store
  console.log('Toast component mounted');
});
</script>

<style scoped>
.toast-enter-active,
.toast-leave-active {
  transition: all 0.3s ease;
}

.toast-enter-from {
  opacity: 0;
  transform: translateX(30px);
}

.toast-leave-to {
  opacity: 0;
  transform: translateX(30px);
}

.animate-fadeIn {
  animation: fadeIn 0.3s ease-in-out;
}

@keyframes fadeIn {
  from { opacity: 0; transform: translateX(30px); }
  to { opacity: 1; transform: translateX(0); }
}
</style>
