// src/pages/Terms.tsx
import { Title } from '@solidjs/meta'
import type { Component } from 'solid-js'

const Terms: Component = () => {
  return (
    <>
      <Title>Terms of Service - Sylphx</Title>
      <div class="min-h-screen bg-white pt-24 pb-16 dark:bg-gray-900">
        <div class="container mx-auto px-4 sm:px-6 lg:px-8">
          <div class="mx-auto max-w-4xl">
            <h1 class="mb-8 text-4xl font-bold text-gray-900 dark:text-white">
              Terms of Service
            </h1>

            <div class="prose prose-lg max-w-none dark:prose-invert">
              <p class="text-sm text-gray-500 dark:text-gray-400">
                Last updated: {new Date().toLocaleDateString()}
              </p>

              <h2>Agreement to Terms</h2>
              <p>
                By accessing or using our website and applications, you agree to be bound by these
                Terms of Service and all applicable laws and regulations.
              </p>

              <h2>Use License</h2>
              <p>
                Permission is granted to temporarily access the materials on Sylphx's website for
                personal, non-commercial transitory viewing only.
              </p>

              <h2>Disclaimer</h2>
              <p>
                The materials on Sylphx's website are provided on an 'as is' basis. Sylphx makes no
                warranties, expressed or implied, and hereby disclaims and negates all other
                warranties.
              </p>

              <h2>Limitations</h2>
              <p>
                In no event shall Sylphx or its suppliers be liable for any damages arising out of the
                use or inability to use the materials on our website.
              </p>

              <h2>Modifications</h2>
              <p>
                Sylphx may revise these terms of service at any time without notice. By using this
                website, you agree to be bound by the current version of these terms.
              </p>

              <h2>Contact</h2>
              <p>
                For questions about these Terms, please contact us at{' '}
                <a href="mailto:legal@sylphx.com">legal@sylphx.com</a>
              </p>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}

export default Terms

// app/terms/page.tsx
export default function TermsPage() {
	return (
		<div className="min-h-screen bg-white pt-24 pb-16">
			<div className="container mx-auto px-4 sm:px-6 lg:px-8">
				<div className="max-w-4xl mx-auto">
					<h1 className="text-4xl md:text-5xl font-bold text-gray-900 mb-6">Terms of Service</h1>
					<p className="text-sm text-gray-500 mb-8">
						Last updated: {new Date().toLocaleDateString()}
					</p>

					<div className="prose prose-lg max-w-none">
						<h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Acceptance of Terms</h2>
						<p className="text-gray-600 leading-relaxed">
							By accessing and using SylphX services, you accept and agree to be bound by the terms
							and provision of this agreement.
						</p>

						<h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Use License</h2>
						<p className="text-gray-600 leading-relaxed">
							Permission is granted to temporarily download one copy of our applications for
							personal, non-commercial transitory viewing only. This is the grant of a license, not
							a transfer of title.
						</p>

						<h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">User Accounts</h2>
						<p className="text-gray-600 leading-relaxed">
							When you create an account with us, you must provide accurate and complete
							information. You are responsible for safeguarding your password and for all activities
							that occur under your account.
						</p>

						<h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Prohibited Uses</h2>
						<p className="text-gray-600 leading-relaxed">You may not use our services:</p>
						<ul className="list-disc pl-6 space-y-2 text-gray-600">
							<li>For any unlawful purpose</li>
							<li>To solicit others to perform unlawful acts</li>
							<li>To violate any international, federal, provincial or state regulations</li>
							<li>To infringe upon our intellectual property rights</li>
							<li>To harass, abuse, or harm another person</li>
						</ul>

						<h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Limitation of Liability</h2>
						<p className="text-gray-600 leading-relaxed">
							In no event shall SylphX be liable for any damages arising out of the use or inability
							to use our services.
						</p>

						<h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Contact Information</h2>
						<p className="text-gray-600 leading-relaxed">
							For questions about these Terms, please contact us at legal@sylphx.com
						</p>
					</div>
				</div>
			</div>
		</div>
	);
}
