// pages/cookies.vue
<template>
  <div class="min-h-screen bg-white dark:bg-gray-900 pt-24 pb-16">
    <div class="container mx-auto px-4 sm:px-6 lg:px-8">
      <!-- Header section -->
      <div class="max-w-4xl mx-auto mb-12">
        <h1 class="text-4xl font-bold text-gray-900 dark:text-white mb-6 text-center">
          Cookie Policy
        </h1>
        <p class="text-xl text-gray-600 dark:text-gray-300 text-center">
          Last updated: May 1, 2025
        </p>
      </div>
      
      <!-- Cookie policy content -->
      <div class="max-w-4xl mx-auto bg-white dark:bg-gray-800 rounded-xl shadow-sm p-8 border border-gray-100 dark:border-gray-700">
        <div class="prose dark:prose-invert max-w-none">
          <h2 class="text-2xl font-bold text-gray-900 dark:text-white mb-4">What Are Cookies</h2>
          <p class="text-gray-600 dark:text-gray-300 mb-6">
            Cookies are small text files that are placed on your computer or mobile device when you visit a website. They are widely used to make websites work more efficiently and provide information to the owners of the site. Cookies enhance user experience by allowing websites to remember your preferences and understand how you use their site.
          </p>
          
          <h2 class="text-2xl font-bold text-gray-900 dark:text-white mb-4">How We Use Cookies</h2>
          <p class="text-gray-600 dark:text-gray-300 mb-4">
            SylphX uses cookies for a variety of purposes, including:
          </p>
          <ul class="mb-6">
            <li class="text-gray-600 dark:text-gray-300 mb-2">
              <strong class="text-gray-900 dark:text-white">Essential cookies:</strong> These are necessary for the website to function properly. They enable basic functions like page navigation, access to secure areas, and remembering your login session.
            </li>
            <li class="text-gray-600 dark:text-gray-300 mb-2">
              <strong class="text-gray-900 dark:text-white">Preference cookies:</strong> These cookies remember your choices and preferences to enhance your browsing experience, such as your preferred language or theme.
            </li>
            <li class="text-gray-600 dark:text-gray-300 mb-2">
              <strong class="text-gray-900 dark:text-white">Analytics cookies:</strong> These help us understand how visitors interact with our website by collecting and reporting information anonymously. This helps us improve our website functionality.
            </li>
            <li class="text-gray-600 dark:text-gray-300 mb-2">
              <strong class="text-gray-900 dark:text-white">Marketing cookies:</strong> These track your online activity to help advertisers deliver more relevant advertising or to limit how many times you see an ad.
            </li>
          </ul>
          
          <h2 class="text-2xl font-bold text-gray-900 dark:text-white mb-4">Types of Cookies We Use</h2>
          <div class="overflow-x-auto mb-6">
            <table class="min-w-full divide-y divide-gray-300 dark:divide-gray-700">
              <thead>
                <tr>
                  <th class="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider bg-gray-50 dark:bg-gray-750">Cookie Name</th>
                  <th class="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider bg-gray-50 dark:bg-gray-750">Purpose</th>
                  <th class="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider bg-gray-50 dark:bg-gray-750">Expiry</th>
                </tr>
              </thead>
              <tbody class="divide-y divide-gray-200 dark:divide-gray-700">
                <tr>
                  <td class="px-4 py-3 text-sm text-gray-900 dark:text-white">session_id</td>
                  <td class="px-4 py-3 text-sm text-gray-600 dark:text-gray-300">Used to maintain your session</td>
                  <td class="px-4 py-3 text-sm text-gray-600 dark:text-gray-300">Session</td>
                </tr>
                <tr>
                  <td class="px-4 py-3 text-sm text-gray-900 dark:text-white">theme_preference</td>
                  <td class="px-4 py-3 text-sm text-gray-600 dark:text-gray-300">Stores your theme preference (light/dark)</td>
                  <td class="px-4 py-3 text-sm text-gray-600 dark:text-gray-300">1 year</td>
                </tr>
                <tr>
                  <td class="px-4 py-3 text-sm text-gray-900 dark:text-white">_ga</td>
                  <td class="px-4 py-3 text-sm text-gray-600 dark:text-gray-300">Google Analytics - Used to distinguish users</td>
                  <td class="px-4 py-3 text-sm text-gray-600 dark:text-gray-300">2 years</td>
                </tr>
                <tr>
                  <td class="px-4 py-3 text-sm text-gray-900 dark:text-white">_gid</td>
                  <td class="px-4 py-3 text-sm text-gray-600 dark:text-gray-300">Google Analytics - Used to distinguish users</td>
                  <td class="px-4 py-3 text-sm text-gray-600 dark:text-gray-300">24 hours</td>
                </tr>
              </tbody>
            </table>
          </div>
          
          <h2 class="text-2xl font-bold text-gray-900 dark:text-white mb-4">Managing Cookies</h2>
          <p class="text-gray-600 dark:text-gray-300 mb-4">
            Most web browsers allow you to control cookies through their settings. You can:
          </p>
          <ul class="mb-6">
            <li class="text-gray-600 dark:text-gray-300 mb-2">Delete cookies from your browser</li>
            <li class="text-gray-600 dark:text-gray-300 mb-2">Block cookies by activating settings on your browser that allow you to refuse all or some cookies</li>
            <li class="text-gray-600 dark:text-gray-300 mb-2">Allow cookies from specific websites that you trust</li>
          </ul>
          <p class="text-gray-600 dark:text-gray-300 mb-6">
            Please note that if you choose to block or delete cookies, you may not be able to access certain areas or features of our website, and some services may not function properly.
          </p>
          
          <h2 class="text-2xl font-bold text-gray-900 dark:text-white mb-4">Changes to Our Cookie Policy</h2>
          <p class="text-gray-600 dark:text-gray-300 mb-6">
            We may update our Cookie Policy from time to time. We will notify you of any changes by posting the new Cookie Policy on this page. You are advised to review this Cookie Policy periodically for any changes.
          </p>
          
          <h2 class="text-2xl font-bold text-gray-900 dark:text-white mb-4">Contact Us</h2>
          <p class="text-gray-600 dark:text-gray-300 mb-6">
            If you have any questions about our Cookie Policy, please contact us at privacy@sylphx.com.
          </p>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
// Define page meta
definePageMeta({
  layout: 'default'
});
</script>

// src/pages/Cookies.tsx
import { Title } from '@solidjs/meta'
import type { Component } from 'solid-js'

const Cookies: Component = () => {
  return (
    <>
      <Title>Cookie Policy - Sylphx</Title>
      <div class="min-h-screen bg-white pt-24 pb-16 dark:bg-gray-900">
        <div class="container mx-auto px-4 sm:px-6 lg:px-8">
          <div class="mx-auto max-w-4xl">
            <h1 class="mb-8 text-4xl font-bold text-gray-900 dark:text-white">Cookie Policy</h1>

            <div class="prose prose-lg max-w-none dark:prose-invert">
              <p class="text-sm text-gray-500 dark:text-gray-400">
                Last updated: {new Date().toLocaleDateString()}
              </p>

              <h2>What Are Cookies</h2>
              <p>
                Cookies are small text files that are placed on your computer or mobile device when
                you visit a website. They are widely used to make websites work more efficiently and
                provide information to the owners of the site.
              </p>

              <h2>How We Use Cookies</h2>
              <p>We use cookies for the following purposes:</p>
              <ul>
                <li>
                  <strong>Essential Cookies:</strong> These cookies are necessary for the website to
                  function properly.
                </li>
                <li>
                  <strong>Analytics Cookies:</strong> These help us understand how visitors interact
                  with our website.
                </li>
                <li>
                  <strong>Preference Cookies:</strong> These remember your preferences and settings.
                </li>
              </ul>

              <h2>Types of Cookies We Use</h2>
              <ul>
                <li>Session cookies: Temporary cookies that expire when you close your browser</li>
                <li>Persistent cookies: Cookies that remain on your device for a set period</li>
              </ul>

              <h2>Managing Cookies</h2>
              <p>
                You can control and/or delete cookies as you wish. You can delete all cookies that are
                already on your computer and you can set most browsers to prevent them from being
                placed.
              </p>

              <h2>Contact</h2>
              <p>
                If you have questions about our use of cookies, please contact us at{' '}
                <a href="mailto:privacy@sylphx.com">privacy@sylphx.com</a>
              </p>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}

export default Cookies
