// app/about/page.tsx
import Link from "next/link";

export default function AboutPage() {
	return (
		<div className="min-h-screen bg-white pt-24 pb-16">
			<div className="container mx-auto px-4 sm:px-6 lg:px-8">
				{/* Header */}
				<div className="max-w-4xl mx-auto mb-16">
					<h1 className="text-4xl md:text-5xl font-bold text-gray-900 mb-6 text-center">
						About SylphX
					</h1>
				</div>

				{/* Company Description */}
				<div className="max-w-4xl mx-auto bg-white rounded-xl shadow-sm p-8 mb-12 border border-gray-100">
					<div className="prose max-w-none">
						<p className="text-lg text-gray-600 leading-relaxed">
							SylphX is a forward-thinking technology company dedicated to creating innovative
							digital experiences that push the boundaries of what&apos;s possible. We specialize in
							developing high-quality, high-performance applications, games, and immersive
							experiences across multiple platforms.
						</p>

						<p className="text-lg text-gray-600 leading-relaxed">
							Founded by a team of passionate developers and designers, our mission is to blend
							cutting-edge technology with intuitive design to create products that are not only
							powerful but also a joy to use.
						</p>

						<h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Our Vision</h2>

						<p className="text-lg text-gray-600 leading-relaxed">
							We envision a future where technology enhances human creativity and connection. Our
							goal is to develop tools and experiences that empower users, spark imagination, and
							create meaningful interactions in both digital and augmented realities.
						</p>

						<h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Our Approach</h2>

						<p className="text-lg text-gray-600 leading-relaxed">
							At SylphX, we believe in a thoughtful, user-centered approach to product development.
							We combine technical excellence with creative innovation, constantly exploring new
							technologies and methodologies to create exceptional digital experiences.
						</p>

						<ul className="list-disc pl-6 space-y-2">
							<li className="text-gray-600">
								<strong className="text-gray-900">Innovation:</strong> Constantly exploring emerging
								technologies like AI, VR, and AR
							</li>
							<li className="text-gray-600">
								<strong className="text-gray-900">Quality:</strong> Rigorous testing and
								optimization for flawless performance
							</li>
							<li className="text-gray-600">
								<strong className="text-gray-900">User Experience:</strong> Intuitive design with
								thoughtful attention to detail
							</li>
							<li className="text-gray-600">
								<strong className="text-gray-900">Accessibility:</strong> Creating products that
								work for everyone
							</li>
						</ul>
					</div>
				</div>

				{/* Contact CTA */}
				<div className="max-w-4xl mx-auto mt-20 text-center">
					<h2 className="text-3xl font-bold text-gray-900 mb-6">Get in Touch</h2>
					<p className="text-xl text-gray-600 mb-8">
						Interested in learning more about SylphX or exploring partnership opportunities?
					</p>
					<Link
						href="/contact"
						className="inline-flex items-center px-6 py-3 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 transition-colors shadow-md hover:shadow-lg"
					>
						Contact Us →
					</Link>
				</div>
			</div>
		</div>
	);
}

// pages/about.vue
<template>
  <div class="min-h-screen bg-white dark:bg-gray-900 pt-24 pb-16">
    <div class="container mx-auto px-4 sm:px-6 lg:px-8">
      <!-- Header section -->
      <div class="max-w-4xl mx-auto mb-16">
        <h1 class="text-4xl md:text-5xl font-bold text-gray-900 dark:text-white mb-6 text-center">
          About SylphX
        </h1>
      </div>
      
      <!-- Company description -->
      <div class="max-w-4xl mx-auto bg-white dark:bg-gray-800 rounded-xl shadow-sm p-8 mb-12 border border-gray-100 dark:border-gray-700">
        <div class="prose dark:prose-invert max-w-none">
          <p class="text-lg text-gray-600 dark:text-gray-300 leading-relaxed">
            SylphX is a forward-thinking technology company dedicated to creating innovative digital experiences 
            that push the boundaries of what's possible. We specialize in developing high-quality, 
            high-performance applications, games, and immersive experiences across multiple platforms.
          </p>
          
          <p class="text-lg text-gray-600 dark:text-gray-300 leading-relaxed">
            Founded by a team of passionate developers and designers, our mission is to blend cutting-edge 
            technology with intuitive design to create products that are not only powerful but also a joy to use.
          </p>
          
          <h2 class="text-2xl font-bold text-gray-900 dark:text-white mt-8 mb-4">Our Vision</h2>
          
          <p class="text-lg text-gray-600 dark:text-gray-300 leading-relaxed">
            We envision a future where technology enhances human creativity and connection. Our goal is to
            develop tools and experiences that empower users, spark imagination, and create meaningful interactions
            in both digital and augmented realities.
          </p>
          
          <h2 class="text-2xl font-bold text-gray-900 dark:text-white mt-8 mb-4">Our Approach</h2>
          
          <p class="text-lg text-gray-600 dark:text-gray-300 leading-relaxed">
            At SylphX, we believe in a thoughtful, user-centered approach to product development. We combine 
            technical excellence with creative innovation, constantly exploring new technologies and methodologies
            to create exceptional digital experiences.
          </p>
          
          <p class="text-lg text-gray-600 dark:text-gray-300 leading-relaxed">
            Our development process emphasizes:
          </p>
          
          <ul>
            <li class="text-gray-600 dark:text-gray-300">
              <strong class="text-gray-900 dark:text-white">Innovation:</strong> 
              Constantly exploring emerging technologies like AI, VR, and AR
            </li>
            <li class="text-gray-600 dark:text-gray-300">
              <strong class="text-gray-900 dark:text-white">Quality:</strong> 
              Rigorous testing and optimization for flawless performance
            </li>
            <li class="text-gray-600 dark:text-gray-300">
              <strong class="text-gray-900 dark:text-white">User Experience:</strong> 
              Intuitive design with thoughtful attention to detail
            </li>
            <li class="text-gray-600 dark:text-gray-300">
              <strong class="text-gray-900 dark:text-white">Accessibility:</strong> 
              Creating products that work for everyone
            </li>
          </ul>
          
          <h2 class="text-2xl font-bold text-gray-900 dark:text-white mt-8 mb-4">Our Team</h2>
          
          <p class="text-lg text-gray-600 dark:text-gray-300 leading-relaxed">
            We are a diverse team of engineers, designers, and visionaries united by a passion for 
            creating exceptional digital experiences. With backgrounds spanning game development, 
            artificial intelligence, mobile applications, and mixed reality, our combined expertise 
            allows us to tackle complex challenges and deliver innovative solutions.
          </p>
        </div>
      </div>
      
      <!-- Team section placeholder -->
      <div class="max-w-6xl mx-auto mt-20">
        <h2 class="text-3xl font-bold text-gray-900 dark:text-white mb-10 text-center">
          Meet Our Leadership Team
        </h2>
        
        <div class="grid grid-cols-1 md:grid-cols-3 gap-8">
          <!-- Team member cards (placeholders) -->
          <div class="bg-white dark:bg-gray-800 rounded-xl overflow-hidden shadow-sm border border-gray-100 dark:border-gray-700">
            <div class="h-48 bg-gray-200 dark:bg-gray-700 flex items-center justify-center">
              <span class="i-carbon-user-avatar text-5xl text-gray-400 dark:text-gray-500"></span>
            </div>
            <div class="p-6">
              <h3 class="text-xl font-bold text-gray-900 dark:text-white mb-1">Jane Doe</h3>
              <p class="text-indigo-600 dark:text-indigo-400 mb-4">Chief Executive Officer</p>
              <p class="text-gray-600 dark:text-gray-300">
                Visionary leader with 15+ years of experience in technology and product development.
              </p>
            </div>
          </div>
          
          <div class="bg-white dark:bg-gray-800 rounded-xl overflow-hidden shadow-sm border border-gray-100 dark:border-gray-700">
            <div class="h-48 bg-gray-200 dark:bg-gray-700 flex items-center justify-center">
              <span class="i-carbon-user-avatar text-5xl text-gray-400 dark:text-gray-500"></span>
            </div>
            <div class="p-6">
              <h3 class="text-xl font-bold text-gray-900 dark:text-white mb-1">John Smith</h3>
              <p class="text-indigo-600 dark:text-indigo-400 mb-4">Chief Technology Officer</p>
              <p class="text-gray-600 dark:text-gray-300">
                Tech innovator specializing in AI and emerging technologies.
              </p>
            </div>
          </div>
          
          <div class="bg-white dark:bg-gray-800 rounded-xl overflow-hidden shadow-sm border border-gray-100 dark:border-gray-700">
            <div class="h-48 bg-gray-200 dark:bg-gray-700 flex items-center justify-center">
              <span class="i-carbon-user-avatar text-5xl text-gray-400 dark:text-gray-500"></span>
            </div>
            <div class="p-6">
              <h3 class="text-xl font-bold text-gray-900 dark:text-white mb-1">Sarah Lee</h3>
              <p class="text-indigo-600 dark:text-indigo-400 mb-4">Creative Director</p>
              <p class="text-gray-600 dark:text-gray-300">
                Award-winning designer with expertise in UX/UI and brand identity.
              </p>
            </div>
          </div>
        </div>
      </div>
      
      <!-- Contact section -->
      <div class="max-w-4xl mx-auto mt-20 text-center">
        <h2 class="text-3xl font-bold text-gray-900 dark:text-white mb-6">
          Get in Touch
        </h2>
        <p class="text-xl text-gray-600 dark:text-gray-300 mb-8">
          Interested in learning more about SylphX or exploring partnership opportunities?
        </p>
        <NuxtLink 
          to="/contact" 
          class="inline-flex items-center px-6 py-3 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 transition-colors shadow-md hover:shadow-lg"
        >
          Contact Us
          <span class="i-carbon-arrow-right ml-2"></span>
        </NuxtLink>
      </div>
    </div>
  </div>
</template>

<script setup>
// Define page meta
definePageMeta({
  layout: 'default'
});
</script>
