// app/careers/page.tsx
export default function CareersPage() {
	const positions = [
		{
			title: "Senior Full-Stack Developer",
			department: "Engineering",
			location: "Remote",
			type: "Full-time",
			description:
				"We're looking for an experienced full-stack developer to help build our next-generation applications.",
		},
		{
			title: "Product Designer",
			department: "Design",
			location: "Remote",
			type: "Full-time",
			description:
				"Join our design team to create beautiful and intuitive user experiences for our products.",
		},
		{
			title: "DevOps Engineer",
			department: "Infrastructure",
			location: "Remote",
			type: "Full-time",
			description:
				"Help us build and maintain scalable infrastructure for millions of users worldwide.",
		},
	];

	return (
		<div className="min-h-screen bg-white pt-24 pb-16">
			<div className="container mx-auto px-4 sm:px-6 lg:px-8">
				<div className="max-w-4xl mx-auto mb-16 text-center">
					<h1 className="text-4xl md:text-5xl font-bold text-gray-900 mb-6">Join Our Team</h1>
					<p className="text-xl text-gray-600">
						We&apos;re always looking for talented individuals to help us build the future of
						digital experiences.
					</p>
				</div>

				<div className="max-w-4xl mx-auto space-y-6">
					{positions.map((position, index) => (
						<div
							key={index}
							className="bg-white border border-gray-200 rounded-lg p-6 hover:shadow-md transition-shadow"
						>
							<div className="flex flex-col md:flex-row md:items-center md:justify-between mb-4">
								<div>
									<h3 className="text-xl font-bold text-gray-900">{position.title}</h3>
									<div className="flex flex-wrap gap-2 mt-2">
										<span className="px-3 py-1 bg-indigo-100 text-indigo-800 rounded-full text-sm">
											{position.department}
										</span>
										<span className="px-3 py-1 bg-gray-100 text-gray-800 rounded-full text-sm">
											{position.location}
										</span>
										<span className="px-3 py-1 bg-green-100 text-green-800 rounded-full text-sm">
											{position.type}
										</span>
									</div>
								</div>
							</div>
							<p className="text-gray-600 mb-4">{position.description}</p>
							<button
								type="button"
								className="px-4 py-2 bg-indigo-600 text-white rounded-md hover:bg-indigo-700 transition-colors"
							>
								Apply Now
							</button>
						</div>
					))}
				</div>

				<div className="max-w-4xl mx-auto mt-16 bg-gradient-to-br from-indigo-50 to-purple-50 rounded-lg p-8">
					<h2 className="text-2xl font-bold text-gray-900 mb-4">Don&apos;t See a Perfect Fit?</h2>
					<p className="text-gray-600 mb-6">
						We&apos;re always interested in meeting talented people. Send us your resume and
						we&apos;ll keep you in mind for future opportunities.
					</p>
					<button
						type="button"
						className="px-6 py-3 bg-indigo-600 text-white rounded-md hover:bg-indigo-700 transition-colors"
					>
						Send Your Resume
					</button>
				</div>
			</div>
		</div>
	);
}

// pages/careers.vue
<template>
  <div class="min-h-screen bg-white dark:bg-gray-900 pt-24 pb-16">
    <div class="container mx-auto px-4 sm:px-6 lg:px-8">
      <!-- Header section -->
      <div class="max-w-4xl mx-auto mb-16">
        <h1 class="text-4xl md:text-5xl font-bold text-gray-900 dark:text-white mb-6 text-center">
          Join Our Team
        </h1>
        <p class="text-xl text-gray-600 dark:text-gray-300 text-center max-w-3xl mx-auto">
          Be part of our mission to create the next generation of digital experiences.
        </p>
      </div>
      
      <!-- Company values section -->
      <div class="max-w-7xl mx-auto mb-20">
        <div class="grid grid-cols-1 md:grid-cols-3 gap-8">
          <div class="bg-white dark:bg-gray-800 rounded-xl p-8 shadow-sm border border-gray-100 dark:border-gray-700">
            <div class="h-12 w-12 bg-indigo-100 dark:bg-indigo-900/30 flex items-center justify-center rounded-lg text-indigo-600 dark:text-indigo-400 mb-6">
              <span class="i-carbon-idea text-2xl"></span>
            </div>
            <h3 class="text-xl font-bold text-gray-900 dark:text-white mb-3">Innovation</h3>
            <p class="text-gray-600 dark:text-gray-300">
              We're constantly pushing boundaries and exploring new technologies to create breakthrough experiences.
            </p>
          </div>
          
          <div class="bg-white dark:bg-gray-800 rounded-xl p-8 shadow-sm border border-gray-100 dark:border-gray-700">
            <div class="h-12 w-12 bg-purple-100 dark:bg-purple-900/30 flex items-center justify-center rounded-lg text-purple-600 dark:text-purple-400 mb-6">
              <span class="i-carbon-collaboration text-2xl"></span>
            </div>
            <h3 class="text-xl font-bold text-gray-900 dark:text-white mb-3">Collaboration</h3>
            <p class="text-gray-600 dark:text-gray-300">
              We believe in the power of diverse teams working together to solve complex challenges.
            </p>
          </div>
          
          <div class="bg-white dark:bg-gray-800 rounded-xl p-8 shadow-sm border border-gray-100 dark:border-gray-700">
            <div class="h-12 w-12 bg-blue-100 dark:bg-blue-900/30 flex items-center justify-center rounded-lg text-blue-600 dark:text-blue-400 mb-6">
              <span class="i-carbon-growth text-2xl"></span>
            </div>
            <h3 class="text-xl font-bold text-gray-900 dark:text-white mb-3">Growth</h3>
            <p class="text-gray-600 dark:text-gray-300">
              We're committed to personal and professional development, helping our team members reach their full potential.
            </p>
          </div>
        </div>
      </div>
      
      <!-- Open positions section -->
      <div class="max-w-5xl mx-auto mb-20">
        <h2 class="text-3xl font-bold text-gray-900 dark:text-white mb-10 text-center">
          Open Positions
        </h2>
        
        <div class="space-y-6">
          <!-- Position 1 -->
          <div class="bg-white dark:bg-gray-800 rounded-xl shadow-sm border border-gray-100 dark:border-gray-700 overflow-hidden">
            <div class="p-6 sm:p-8">
              <div class="flex flex-col sm:flex-row sm:items-center sm:justify-between">
                <div>
                  <h3 class="text-xl font-bold text-gray-900 dark:text-white">Senior Frontend Engineer</h3>
                  <div class="mt-1 flex flex-wrap gap-2">
                    <span class="inline-flex items-center px-3 py-1 rounded-full text-xs font-medium bg-indigo-100 text-indigo-800 dark:bg-indigo-900/30 dark:text-indigo-300">
                      Full-time
                    </span>
                    <span class="inline-flex items-center px-3 py-1 rounded-full text-xs font-medium bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-300">
                      Remote
                    </span>
                    <span class="inline-flex items-center px-3 py-1 rounded-full text-xs font-medium bg-purple-100 text-purple-800 dark:bg-purple-900/30 dark:text-purple-300">
                      Engineering
                    </span>
                  </div>
                </div>
                <button class="mt-4 sm:mt-0 inline-flex items-center px-4 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                  Apply Now
                </button>
              </div>
              
              <div class="mt-6">
                <h4 class="text-sm font-medium text-gray-900 dark:text-white">Description</h4>
                <p class="mt-2 text-gray-600 dark:text-gray-300">
                  We're looking for a Senior Frontend Engineer to help build the next generation of our web and mobile applications. You'll work on creating beautiful, responsive, and accessible user interfaces using Vue.js and other modern web technologies.
                </p>
              </div>
              
              <div class="mt-6">
                <h4 class="text-sm font-medium text-gray-900 dark:text-white">Requirements</h4>
                <ul class="mt-2 text-gray-600 dark:text-gray-300 list-disc pl-5 space-y-1">
                  <li>5+ years of experience in frontend development</li>
                  <li>Strong knowledge of Vue.js or similar modern frameworks</li>
                  <li>Experience with responsive design and cross-browser compatibility</li>
                  <li>Understanding of modern CSS practices and tools</li>
                  <li>Experience with state management in complex applications</li>
                </ul>
              </div>
            </div>
          </div>
          
          <!-- Position 2 -->
          <div class="bg-white dark:bg-gray-800 rounded-xl shadow-sm border border-gray-100 dark:border-gray-700 overflow-hidden">
            <div class="p-6 sm:p-8">
              <div class="flex flex-col sm:flex-row sm:items-center sm:justify-between">
                <div>
                  <h3 class="text-xl font-bold text-gray-900 dark:text-white">Machine Learning Engineer</h3>
                  <div class="mt-1 flex flex-wrap gap-2">
                    <span class="inline-flex items-center px-3 py-1 rounded-full text-xs font-medium bg-indigo-100 text-indigo-800 dark:bg-indigo-900/30 dark:text-indigo-300">
                      Full-time
                    </span>
                    <span class="inline-flex items-center px-3 py-1 rounded-full text-xs font-medium bg-blue-100 text-blue-800 dark:bg-blue-900/30 dark:text-blue-300">
                      San Francisco
                    </span>
                    <span class="inline-flex items-center px-3 py-1 rounded-full text-xs font-medium bg-amber-100 text-amber-800 dark:bg-amber-900/30 dark:text-amber-300">
                      AI Team
                    </span>
                  </div>
                </div>
                <button class="mt-4 sm:mt-0 inline-flex items-center px-4 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                  Apply Now
                </button>
              </div>
              
              <div class="mt-6">
                <h4 class="text-sm font-medium text-gray-900 dark:text-white">Description</h4>
                <p class="mt-2 text-gray-600 dark:text-gray-300">
                  We're seeking a Machine Learning Engineer to help develop and deploy the AI systems that power our applications. You'll work on creating intelligent systems that can understand user behavior, generate content, and enhance user experiences.
                </p>
              </div>
              
              <div class="mt-6">
                <h4 class="text-sm font-medium text-gray-900 dark:text-white">Requirements</h4>
                <ul class="mt-2 text-gray-600 dark:text-gray-300 list-disc pl-5 space-y-1">
                  <li>3+ years of experience in machine learning</li>
                  <li>Strong knowledge of deep learning frameworks (TensorFlow, PyTorch)</li>
                  <li>Experience with natural language processing and computer vision</li>
                  <li>Understanding of ML model deployment and optimization</li>
                  <li>Strong mathematical and statistical background</li>
                </ul>
              </div>
            </div>
          </div>
          
          <!-- Position 3 -->
          <div class="bg-white dark:bg-gray-800 rounded-xl shadow-sm border border-gray-100 dark:border-gray-700 overflow-hidden">
            <div class="p-6 sm:p-8">
              <div class="flex flex-col sm:flex-row sm:items-center sm:justify-between">
                <div>
                  <h3 class="text-xl font-bold text-gray-900 dark:text-white">Product Designer</h3>
                  <div class="mt-1 flex flex-wrap gap-2">
                    <span class="inline-flex items-center px-3 py-1 rounded-full text-xs font-medium bg-indigo-100 text-indigo-800 dark:bg-indigo-900/30 dark:text-indigo-300">
                      Full-time
                    </span>
                    <span class="inline-flex items-center px-3 py-1 rounded-full text-xs font-medium bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-300">
                      Remote
                    </span>
                    <span class="inline-flex items-center px-3 py-1 rounded-full text-xs font-medium bg-pink-100 text-pink-800 dark:bg-pink-900/30 dark:text-pink-300">
                      Design
                    </span>
                  </div>
                </div>
                <button class="mt-4 sm:mt-0 inline-flex items-center px-4 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                  Apply Now
                </button>
              </div>
              
              <div class="mt-6">
                <h4 class="text-sm font-medium text-gray-900 dark:text-white">Description</h4>
                <p class="mt-2 text-gray-600 dark:text-gray-300">
                  We're looking for a Product Designer to create beautiful, intuitive interfaces for our applications. You'll work closely with product managers and engineers to design experiences that delight users and solve complex problems.
                </p>
              </div>
              
              <div class="mt-6">
                <h4 class="text-sm font-medium text-gray-900 dark:text-white">Requirements</h4>
                <ul class="mt-2 text-gray-600 dark:text-gray-300 list-disc pl-5 space-y-1">
                  <li>3+ years of experience in product design</li>
                  <li>Strong portfolio demonstrating UI/UX design skills</li>
                  <li>Experience with design systems and component libraries</li>
                  <li>Proficiency with modern design tools (Figma, Sketch, etc.)</li>
                  <li>Understanding of user-centered design principles</li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        
        <div class="text-center mt-12">
          <p class="text-gray-600 dark:text-gray-300 mb-6">
            Don't see a position that matches your skills? We're always looking for talented people to join our team.
          </p>
          <a href="mailto:careers@sylphx.com" class="inline-flex items-center px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-md shadow-sm text-sm font-medium text-gray-700 dark:text-gray-300 bg-white dark:bg-gray-800 hover:bg-gray-50 dark:hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
            <span class="i-carbon-email mr-2"></span>
            Send us your resume
          </a>
        </div>
      </div>
      
      <!-- Benefits section -->
      <div class="max-w-7xl mx-auto">
        <h2 class="text-3xl font-bold text-gray-900 dark:text-white mb-10 text-center">
          Benefits & Perks
        </h2>
        
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
          <div class="bg-white dark:bg-gray-800 rounded-xl p-6 shadow-sm border border-gray-100 dark:border-gray-700 text-center">
            <div class="h-12 w-12 mx-auto bg-green-100 dark:bg-green-900/30 flex items-center justify-center rounded-lg text-green-600 dark:text-green-400 mb-6">
              <span class="i-carbon-medical-insurance text-2xl"></span>
            </div>
            <h3 class="text-lg font-bold text-gray-900 dark:text-white mb-3">Health Insurance</h3>
            <p class="text-gray-600 dark:text-gray-300">
              Comprehensive health, dental, and vision coverage for you and your dependents.
            </p>
          </div>
          
          <div class="bg-white dark:bg-gray-800 rounded-xl p-6 shadow-sm border border-gray-100 dark:border-gray-700 text-center">
            <div class="h-12 w-12 mx-auto bg-blue-100 dark:bg-blue-900/30 flex items-center justify-center rounded-lg text-blue-600 dark:text-blue-400 mb-6">
              <span class="i-carbon-calendar text-2xl"></span>
            </div>
            <h3 class="text-lg font-bold text-gray-900 dark:text-white mb-3">Flexible Time Off</h3>
            <p class="text-gray-600 dark:text-gray-300">
              Take time when you need it with our flexible and generous paid time off policy.
            </p>
          </div>
          
          <div class="bg-white dark:bg-gray-800 rounded-xl p-6 shadow-sm border border-gray-100 dark:border-gray-700 text-center">
            <div class="h-12 w-12 mx-auto bg-purple-100 dark:bg-purple-900/30 flex items-center justify-center rounded-lg text-purple-600 dark:text-purple-400 mb-6">
              <span class="i-carbon-education text-2xl"></span>
            </div>
            <h3 class="text-lg font-bold text-gray-900 dark:text-white mb-3">Learning Budget</h3>
            <p class="text-gray-600 dark:text-gray-300">
              Annual budget for courses, books, conferences, and other learning opportunities.
            </p>
          </div>
          
          <div class="bg-white dark:bg-gray-800 rounded-xl p-6 shadow-sm border border-gray-100 dark:border-gray-700 text-center">
            <div class="h-12 w-12 mx-auto bg-amber-100 dark:bg-amber-900/30 flex items-center justify-center rounded-lg text-amber-600 dark:text-amber-400 mb-6">
              <span class="i-carbon-laptop text-2xl"></span>
            </div>
            <h3 class="text-lg font-bold text-gray-900 dark:text-white mb-3">Remote Work</h3>
            <p class="text-gray-600 dark:text-gray-300">
              Flexible work arrangements with the option to work remotely or in our offices.
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
// Define page meta
definePageMeta({
  layout: 'default'
});
</script>
