// src/app/contact/page.tsx
'use client'

import { useState } from 'react'
import { successToast } from '@/stores/toast'

export default function ContactPage() {
  const [formData, setFormData] = useState({
    name: '',
    email: '',
    subject: '',
    message: '',
  })
  const [isSubmitting, setIsSubmitting] = useState(false)

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setIsSubmitting(true)

    // Simulate form submission
    await new Promise((resolve) => setTimeout(resolve, 1000))

    successToast('Message sent successfully! We will get back to you soon.')
    setFormData({ name: '', email: '', subject: '', message: '' })
    setIsSubmitting(false)
  }

  return (
    <div className="min-h-screen bg-white pt-24 pb-16 dark:bg-gray-900">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8">
        <div className="mx-auto mb-16 max-w-4xl text-center">
          <h1 className="mb-6 text-4xl font-bold text-gray-900 dark:text-white md:text-5xl">
            Contact Us
          </h1>
          <p className="text-lg text-gray-600 dark:text-gray-300">
            Have a question or want to work together? We'd love to hear from you.
          </p>
        </div>

        <div className="mx-auto grid max-w-6xl grid-cols-1 gap-12 lg:grid-cols-2">
          {/* Contact Form */}
          <div className="rounded-xl border border-gray-100 bg-white p-8 shadow-sm dark:border-gray-700 dark:bg-gray-800">
            <h2 className="mb-6 text-2xl font-bold text-gray-900 dark:text-white">
              Send us a message
            </h2>
            <form onSubmit={handleSubmit} className="space-y-6">
              <div>
                <label
                  htmlFor="name"
                  className="mb-2 block text-sm font-medium text-gray-900 dark:text-white"
                >
                  Name
                </label>
                <input
                  type="text"
                  id="name"
                  required
                  value={formData.name}
                  onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                  className="w-full rounded-lg border border-gray-300 bg-white px-4 py-2 text-gray-900 focus:border-indigo-500 focus:outline-none focus:ring-1 focus:ring-indigo-500 dark:border-gray-600 dark:bg-gray-700 dark:text-white"
                />
              </div>

              <div>
                <label
                  htmlFor="email"
                  className="mb-2 block text-sm font-medium text-gray-900 dark:text-white"
                >
                  Email
                </label>
                <input
                  type="email"
                  id="email"
                  required
                  value={formData.email}
                  onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                  className="w-full rounded-lg border border-gray-300 bg-white px-4 py-2 text-gray-900 focus:border-indigo-500 focus:outline-none focus:ring-1 focus:ring-indigo-500 dark:border-gray-600 dark:bg-gray-700 dark:text-white"
                />
              </div>

              <div>
                <label
                  htmlFor="subject"
                  className="mb-2 block text-sm font-medium text-gray-900 dark:text-white"
                >
                  Subject
                </label>
                <input
                  type="text"
                  id="subject"
                  required
                  value={formData.subject}
                  onChange={(e) => setFormData({ ...formData, subject: e.target.value })}
                  className="w-full rounded-lg border border-gray-300 bg-white px-4 py-2 text-gray-900 focus:border-indigo-500 focus:outline-none focus:ring-1 focus:ring-indigo-500 dark:border-gray-600 dark:bg-gray-700 dark:text-white"
                />
              </div>

              <div>
                <label
                  htmlFor="message"
                  className="mb-2 block text-sm font-medium text-gray-900 dark:text-white"
                >
                  Message
                </label>
                <textarea
                  id="message"
                  required
                  rows={6}
                  value={formData.message}
                  onChange={(e) => setFormData({ ...formData, message: e.target.value })}
                  className="w-full rounded-lg border border-gray-300 bg-white px-4 py-2 text-gray-900 focus:border-indigo-500 focus:outline-none focus:ring-1 focus:ring-indigo-500 dark:border-gray-600 dark:bg-gray-700 dark:text-white"
                />
              </div>

              <button
                type="submit"
                disabled={isSubmitting}
                className="w-full rounded-lg bg-indigo-600 px-6 py-3 font-medium text-white transition-colors hover:bg-indigo-700 disabled:cursor-not-allowed disabled:opacity-50"
              >
                {isSubmitting ? 'Sending...' : 'Send Message'}
              </button>
            </form>
          </div>

          {/* Contact Information */}
          <div className="space-y-8">
            <div className="rounded-xl border border-gray-100 bg-white p-6 shadow-sm dark:border-gray-700 dark:bg-gray-800">
              <div className="mb-4 flex h-12 w-12 items-center justify-center rounded-full bg-indigo-100 dark:bg-indigo-900">
                <span className="text-2xl">📧</span>
              </div>
              <h3 className="mb-2 text-lg font-bold text-gray-900 dark:text-white">Email</h3>
              <p className="text-gray-600 dark:text-gray-300">hi@sylphx.com</p>
            </div>

            <div className="rounded-xl border border-gray-100 bg-white p-6 shadow-sm dark:border-gray-700 dark:bg-gray-800">
              <div className="mb-4 flex h-12 w-12 items-center justify-center rounded-full bg-purple-100 dark:bg-purple-900">
                <span className="text-2xl">🐦</span>
              </div>
              <h3 className="mb-2 text-lg font-bold text-gray-900 dark:text-white">Social Media</h3>
              <p className="text-gray-600 dark:text-gray-300">@sylphxlab on Twitter</p>
              <p className="text-gray-600 dark:text-gray-300">@sylphxltd on GitHub</p>
            </div>

            <div className="rounded-xl border border-gray-100 bg-white p-6 shadow-sm dark:border-gray-700 dark:bg-gray-800">
              <div className="mb-4 flex h-12 w-12 items-center justify-center rounded-full bg-blue-100 dark:bg-blue-900">
                <span className="text-2xl">💼</span>
              </div>
              <h3 className="mb-2 text-lg font-bold text-gray-900 dark:text-white">Careers</h3>
              <p className="text-gray-600 dark:text-gray-300">
                Interested in joining our team? Check out our{' '}
                <a href="/careers" className="text-indigo-600 hover:underline dark:text-indigo-400">
                  careers page
                </a>
                .
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

// pages/contact.vue
<template>
  <div class="min-h-screen bg-white dark:bg-gray-900 pt-24 pb-16">
    <div class="container mx-auto px-4 sm:px-6 lg:px-8">
      <!-- Header section -->
      <div class="max-w-4xl mx-auto mb-16">
        <h1 class="text-4xl md:text-5xl font-bold text-gray-900 dark:text-white mb-6 text-center">
          Contact Us
        </h1>
        <p class="text-xl text-gray-600 dark:text-gray-300 text-center max-w-3xl mx-auto">
          Have questions, feedback, or interested in our products? We'd love to hear from you.
        </p>
      </div>

      <div class="grid grid-cols-1 lg:grid-cols-5 gap-12 max-w-6xl mx-auto">
        <!-- Contact information -->
        <div class="lg:col-span-2">
          <div class="bg-white dark:bg-gray-800 rounded-xl shadow-sm p-8 border border-gray-100 dark:border-gray-700 h-full">
            <h2 class="text-2xl font-bold text-gray-900 dark:text-white mb-6">Get in Touch</h2>
            
            <div class="space-y-6">
              <div class="flex">
                <div class="flex-shrink-0">
                  <div class="h-10 w-10 rounded-full bg-indigo-100 dark:bg-indigo-900/50 flex items-center justify-center text-indigo-600 dark:text-indigo-400">
                    <span class="i-carbon-email text-xl"></span>
                  </div>
                </div>
                <div class="ml-4">
                  <h3 class="text-lg font-medium text-gray-900 dark:text-white">Email</h3>
                  <p class="mt-1 text-gray-600 dark:text-gray-300">
                    <a href="mailto:contact@sylphx.com" class="hover:text-indigo-600 dark:hover:text-indigo-400">
                      contact@sylphx.com
                    </a>
                  </p>
                  <p class="mt-1 text-sm text-gray-500 dark:text-gray-400">
                    We'll respond within 24 hours
                  </p>
                </div>
              </div>
              
              <div class="flex">
                <div class="flex-shrink-0">
                  <div class="h-10 w-10 rounded-full bg-indigo-100 dark:bg-indigo-900/50 flex items-center justify-center text-indigo-600 dark:text-indigo-400">
                    <span class="i-carbon-chat text-xl"></span>
                  </div>
                </div>
                <div class="ml-4">
                  <h3 class="text-lg font-medium text-gray-900 dark:text-white">Live Chat</h3>
                  <p class="mt-1 text-gray-600 dark:text-gray-300">
                    Our team is available Monday-Friday
                  </p>
                  <p class="mt-1 text-sm text-gray-500 dark:text-gray-400">
                    9:00 AM - 6:00 PM ET
                  </p>
                </div>
              </div>
              
              <div class="flex">
                <div class="flex-shrink-0">
                  <div class="h-10 w-10 rounded-full bg-indigo-100 dark:bg-indigo-900/50 flex items-center justify-center text-indigo-600 dark:text-indigo-400">
                    <span class="i-carbon-location text-xl"></span>
                  </div>
                </div>
                <div class="ml-4">
                  <h3 class="text-lg font-medium text-gray-900 dark:text-white">Office</h3>
                  <p class="mt-1 text-gray-600 dark:text-gray-300">
                    123 Innovation Way<br>
                    San Francisco, CA 94107
                  </p>
                </div>
              </div>
              
              <div class="flex">
                <div class="flex-shrink-0">
                  <div class="h-10 w-10 rounded-full bg-indigo-100 dark:bg-indigo-900/50 flex items-center justify-center text-indigo-600 dark:text-indigo-400">
                    <span class="i-carbon-phone text-xl"></span>
                  </div>
                </div>
                <div class="ml-4">
                  <h3 class="text-lg font-medium text-gray-900 dark:text-white">Phone</h3>
                  <p class="mt-1 text-gray-600 dark:text-gray-300">
                    <a href="tel:+14155550123" class="hover:text-indigo-600 dark:hover:text-indigo-400">
                      +1 (415) 555-0123
                    </a>
                  </p>
                  <p class="mt-1 text-sm text-gray-500 dark:text-gray-400">
                    Monday-Friday, 9AM-6PM ET
                  </p>
                </div>
              </div>
            </div>
            
            <div class="mt-10">
              <h3 class="text-lg font-medium text-gray-900 dark:text-white mb-3">Connect with us</h3>
              <div class="flex space-x-4">
                <a href="#" class="h-10 w-10 rounded-full bg-indigo-100 dark:bg-indigo-900/30 flex items-center justify-center text-indigo-600 dark:text-indigo-400 hover:bg-indigo-200 dark:hover:bg-indigo-900/50 transition-colors">
                  <span class="i-carbon-logo-twitter text-xl"></span>
                </a>
                <a href="#" class="h-10 w-10 rounded-full bg-indigo-100 dark:bg-indigo-900/30 flex items-center justify-center text-indigo-600 dark:text-indigo-400 hover:bg-indigo-200 dark:hover:bg-indigo-900/50 transition-colors">
                  <span class="i-carbon-logo-facebook text-xl"></span>
                </a>
                <a href="#" class="h-10 w-10 rounded-full bg-indigo-100 dark:bg-indigo-900/30 flex items-center justify-center text-indigo-600 dark:text-indigo-400 hover:bg-indigo-200 dark:hover:bg-indigo-900/50 transition-colors">
                  <span class="i-carbon-logo-instagram text-xl"></span>
                </a>
                <a href="#" class="h-10 w-10 rounded-full bg-indigo-100 dark:bg-indigo-900/30 flex items-center justify-center text-indigo-600 dark:text-indigo-400 hover:bg-indigo-200 dark:hover:bg-indigo-900/50 transition-colors">
                  <span class="i-carbon-logo-linkedin text-xl"></span>
                </a>
              </div>
            </div>
          </div>
        </div>
        
        <!-- Contact form -->
        <div class="lg:col-span-3">
          <div class="bg-white dark:bg-gray-800 rounded-xl shadow-sm p-8 border border-gray-100 dark:border-gray-700">
            <h2 class="text-2xl font-bold text-gray-900 dark:text-white mb-6">Send us a Message</h2>
            
            <form @submit.prevent="submitForm" class="space-y-6">
              <div class="grid grid-cols-1 sm:grid-cols-2 gap-6">
                <div>
                  <label for="first-name" class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                    First name
                  </label>
                  <input 
                    id="first-name" 
                    v-model="form.firstName"
                    type="text" 
                    class="block w-full px-4 py-3 border border-gray-200 dark:border-gray-700 rounded-md bg-white dark:bg-gray-800 text-gray-900 dark:text-white placeholder-gray-500 dark:placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-indigo-500 transition-colors"
                    required
                  />
                </div>
                
                <div>
                  <label for="last-name" class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                    Last name
                  </label>
                  <input 
                    id="last-name" 
                    v-model="form.lastName"
                    type="text" 
                    class="block w-full px-4 py-3 border border-gray-200 dark:border-gray-700 rounded-md bg-white dark:bg-gray-800 text-gray-900 dark:text-white placeholder-gray-500 dark:placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-indigo-500 transition-colors"
                    required
                  />
                </div>
              </div>
              
              <div>
                <label for="email" class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                  Email
                </label>
                <input 
                  id="email" 
                  v-model="form.email"
                  type="email" 
                  class="block w-full px-4 py-3 border border-gray-200 dark:border-gray-700 rounded-md bg-white dark:bg-gray-800 text-gray-900 dark:text-white placeholder-gray-500 dark:placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-indigo-500 transition-colors"
                  required
                />
              </div>
              
              <div>
                <label for="subject" class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                  Subject
                </label>
                <select 
                  id="subject" 
                  v-model="form.subject"
                  class="block w-full px-4 py-3 border border-gray-200 dark:border-gray-700 rounded-md bg-white dark:bg-gray-800 text-gray-900 dark:text-white placeholder-gray-500 dark:placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-indigo-500 transition-colors"
                  required
                >
                  <option value="" disabled selected>Please select</option>
                  <option value="General Inquiry">General Inquiry</option>
                  <option value="Product Support">Product Support</option>
                  <option value="Partnership">Partnership</option>
                  <option value="Press">Press</option>
                  <option value="Careers">Careers</option>
                </select>
              </div>
              
              <div>
                <label for="message" class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                  Message
                </label>
                <textarea 
                  id="message" 
                  v-model="form.message"
                  rows="6" 
                  class="block w-full px-4 py-3 border border-gray-200 dark:border-gray-700 rounded-md bg-white dark:bg-gray-800 text-gray-900 dark:text-white placeholder-gray-500 dark:placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-indigo-500 transition-colors"
                  required
                ></textarea>
              </div>
              
              <div class="flex items-start">
                <div class="flex items-center h-5">
                  <input 
                    id="privacy" 
                    v-model="form.privacyAccepted"
                    type="checkbox" 
                    class="h-4 w-4 text-indigo-600 focus:ring-indigo-500 border-gray-300 rounded"
                    required
                  />
                </div>
                <div class="ml-3 text-sm">
                  <label for="privacy" class="text-gray-600 dark:text-gray-400">
                    I agree to the 
                    <NuxtLink to="/privacy" class="text-indigo-600 dark:text-indigo-400 hover:underline">Privacy Policy</NuxtLink>
                    and consent to having my data processed.
                  </label>
                </div>
              </div>
              
              <div>
                <button 
                  type="submit" 
                  :disabled="isSubmitting"
                  :class="[
                    'w-full flex justify-center items-center px-6 py-3 border border-transparent rounded-md shadow-sm text-base font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 transition-colors',
                    isSubmitting ? 'opacity-75 cursor-not-allowed' : ''
                  ]"
                >
                  <span v-if="isSubmitting" class="i-carbon-circle-dash animate-spin mr-2"></span>
                  {{ isSubmitting ? 'Sending...' : 'Send Message' }}
                </button>
              </div>
            </form>
            
            <div v-if="formSubmitted" class="mt-6 p-4 bg-green-50 dark:bg-green-900/20 rounded-md">
              <div class="flex">
                <div class="flex-shrink-0">
                  <span class="i-carbon-checkmark-filled text-green-600 dark:text-green-400 text-xl"></span>
                </div>
                <div class="ml-3">
                  <h3 class="text-sm font-medium text-green-800 dark:text-green-300">
                    Message Sent!
                  </h3>
                  <div class="mt-2 text-sm text-green-700 dark:text-green-400">
                    <p>
                      Thank you for reaching out. We'll get back to you as soon as possible.
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      
      <!-- Map section -->
      <div class="max-w-6xl mx-auto mt-20">
        <div class="bg-white dark:bg-gray-800 rounded-xl shadow-sm overflow-hidden border border-gray-100 dark:border-gray-700">
          <div class="aspect-video bg-gray-100 dark:bg-gray-700 flex items-center justify-center">
            <!-- Placeholder for an actual map component -->
            <div class="text-center p-10">
              <span class="i-carbon-map text-5xl text-gray-400 dark:text-gray-500 mb-4 block"></span>
              <p class="text-gray-600 dark:text-gray-400 text-lg">
                Interactive map would be displayed here
              </p>
              <p class="text-gray-500 dark:text-gray-500 text-sm mt-2">
                123 Innovation Way, San Francisco, CA 94107
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, reactive } from 'vue';

// Define page meta
definePageMeta({
  layout: 'default'
});

// Form state
const form = reactive({
  firstName: '',
  lastName: '',
  email: '',
  subject: '',
  message: '',
  privacyAccepted: false
});

const isSubmitting = ref(false);
const formSubmitted = ref(false);

// Form submission
const submitForm = async () => {
  isSubmitting.value = true;
  
  // Simulate API call with delay
  await new Promise(resolve => setTimeout(resolve, 1500));
  
  // In a real app, you would send the form data to your backend
  console.log('Form submitted:', form);
  
  // Reset form after submission
  formSubmitted.value = true;
  isSubmitting.value = false;
  
  // Reset form fields
  form.firstName = '';
  form.lastName = '';
  form.email = '';
  form.subject = '';
  form.message = '';
  form.privacyAccepted = false;
  
  // Hide success message after 5 seconds
  setTimeout(() => {
    formSubmitted.value = false;
  }, 5000);
};
</script>
